name: laypa
channels:
  # - default
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3
  - numpy
  - llvm-openmp<16 # For CPU affinity pytorch issues (https://github.com/pytorch/pytorch/issues/102269)
  - pytorch
  - cuda-toolkit
  - torchvision
  - opencv
  - matplotlib
  - scipy
  - pip
  - flask
  - prometheus_client
  - imagesize
  - timm
  - gunicorn
  - pillow
  - shapely
  - natsort
  # - pygments #Optional for colors
  - pip:
      - "git+https://github.com/facebookresearch/detectron2.git"
      - "git+https://github.com/cocodataset/panopticapi.git"
      - ./models/pixel_decoder/ops/
