name: laypa
channels:
  - default
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3
  - numpy=1
  - llvm-openmp<16 # For CPU affinity pytorch issues (https://github.com/pytorch/pytorch/issues/102269)
  - pytorch
  - pytorch-cuda
  - cuda-toolkit
  - torchvision
  - opencv
  - matplotlib
  - scipy
  - pip=23
  - flask
  - prometheus_client
  - imagesize
  - timm
  - gunicorn
  - pillow
  - shapely
  - natsort
  # - jpeg # For loading JPEG2000 images
  # - pygments #Optional for colors
  - pip:
      - distinctipy
      - git+https://github.com/facebookresearch/detectron2.git
      - git+https://github.com/cocodataset/panopticapi.git
      - ./models/pixel_decoder/ops/
